lr : [0.0001]
StepLR_setp: [200]
StepLR_gamma: 0.5
in_channels : [[1,8,8,16]]
out_channels: [[8,8,16,16]]
kernel_size: [[5,5,3,3]]
batch_size: 128
loss_weight: [0.025, 0.25, 4, 10]
signal_length: 5890
pool_size: 2
